services:
  - type: web
    name: hotel-price-comparator
    env: node
    region: singapore
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
